In [2]:
import numpy as np

## 배열 간 연산
- 동일한 인덱스끼리 연산
- 넘파이 배열 간 연산을 할 때 배열의 길이는 동일해야 한다.

In [5]:
# --------------------------------------------------
# 넘파이배열 간 연산 --> 동일한 인덱스끼리 연산
# 배열의 길이가 다른 경우 배열간 연산을 할 수 없음.
# --------------------------------------------------

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1)
print(arr2)

[1 2 3]
[4 5 6]


In [6]:
# 배열 간 덧셈연산
print('arr1>>>', arr1)
print('arr2>>>', arr2)
print('----- arr1+arr2 -----')
arr1+arr2

arr1>>> [1 2 3]
arr2>>> [4 5 6]
----- arr1+arr2 -----


array([5, 7, 9])

In [7]:
# 배열 간 뺄셈연산
print('arr1>>>', arr1)
print('arr2>>>', arr2)
print('----- arr1-arr2 -----')
arr1-arr2

arr1>>> [1 2 3]
arr2>>> [4 5 6]
----- arr1-arr2 -----


array([-3, -3, -3])

In [8]:
# 배열 비교 연산
print('arr1>>>', arr1)
print('arr2>>>', arr2)
print('----- arr1>arr2 -----')
arr1>arr2

arr1>>> [1 2 3]
arr2>>> [4 5 6]
----- arr1>arr2 -----


array([False, False, False])

## 브로드캐스팅 연산
* 서로 다른 모양의 배열끼리 연산     


> **조건**   
> * 배열과 스칼라 간 연산     
> * 두 배열의 열의 갯수가 같고, 한 배열의 차원이 1차원일 때     
> * 첫번째 배열의 행의 개수와 두번째 배열의 열의 >개수가 같을 때

In [9]:
# --------------------------
# 배열과 스칼라 간 연산
# --------------------------

arr = np.array([[1,2,3],[4,5,6]])
print('arr>>>\n', arr)
print('\n----- arr+1 -----\n')
print(arr+1)

arr>>>
 [[1 2 3]
 [4 5 6]]

----- arr+1 -----

[[2 3 4]
 [5 6 7]]


In [10]:
# --------------------------
# 한 배열의 차원이 1차원일 때
# --------------------------

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3])

print('arr1>>>\n', arr1)
print('\narr2>>>\n', arr2, '\n')

print('----arr1+arr2------')
print(arr1 + arr2)

arr1>>>
 [[1 2 3]
 [4 5 6]]

arr2>>>
 [1 2 3] 

----arr1+arr2------
[[2 4 6]
 [5 7 9]]


In [11]:
# --------------------------
# 첫번째 배열의 행의 개수와 두번째 배열의 열의 개수가 같을 때
# --------------------------

arr1 = np.array([[1],[2],[3]])
arr2 = np.array([4,5,6])
print('arr1>>>\n', arr1)
print('\narr2>>>\n', arr2, '\n')

print('----arr1+arr2------')
print(arr1 + arr2)

arr1>>>
 [[1]
 [2]
 [3]]

arr2>>>
 [4 5 6] 

----arr1+arr2------
[[5 6 7]
 [6 7 8]
 [7 8 9]]


## ZeroDivision
- 에러를 발생시키지 않고 경고만 표시한다.

In [ ]:
# 1/0 
# --> ZeroDivisionError  

In [12]:
arr = np.array([0, 1, 2])
print(1/arr)
print(0/arr)

[inf 1.  0.5]
[nan  0.  0.]


C:\Users\User\AppData\Local\Temp\ipykernel_6016\4013972719.py:2: RuntimeWarning: divide by zero encountered in divide
  print(1/arr)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\4013972719.py:3: RuntimeWarning: invalid value encountered in divide
  print(0/arr)


## 집계함수
* 주요 집계함수
    * `sum()` : 합계
    * `mean()` : 평균
    * `median()` : 중앙값
    * `min()` : 최소값
    * `max()` : 최대값
    * `std()` : 표준편차
    * `var()` : 분산
    * `percentile()` : 백분위수
    * `argmin()` : 최소값의 인덱스
    * `argmax()` : 최대값의 인덱스
    * `cumsum()` : 누적합계
    * `cumrod()` : 누적곱
    * `ptp()` : 최대값-최소값(범위값)
    * `unique()` : 유일한 값(중복제거)
* 함수의 형태와 배열의 메서드 형태로 사용할 수 있다.
    * `np.집계함수(배열)`
    * `배열.집계함수()`
* 축 설정
    * `axis=0` 
        * 행이 늘어나는 방향(열 방향)으로 집계
        * 각 열에 대해 하나의 결과
    * `axis=1` 
        * 열이 늘어나는 방향(행 방향)으로 집계 
        * 각 행에 대해 하나의 결과

In [17]:
# --------------------
# 합계(sum)
# --------------------

arr = np.array([[1, 2, 3], [4, 5, 6]])
print('arr>>>\n', arr)
print('----------')
print('전체 합계 :', np.sum(arr))
print('열별 합계(axis=0) :', np.sum(arr, axis=0))
print('행별 합계(axis=1) :', np.sum(arr, axis=1))

arr>>>
 [[1 2 3]
 [4 5 6]]
----------
전체 합계 : 21
열별 합계(axis=0) : [5 7 9]
행별 합계(axis=1) : [ 6 15]


In [18]:
# --------------------
# 평균(mean)
# --------------------

arr = np.array([[1, 2, 3], [4, 5, 6]])
print('arr>>>\n', arr)
print('----------')
print('전체 평균 :', np.mean(arr))
print('열별 평균(axis=0) :', np.mean(arr, axis=0))
print('행별 평균(axis=1) :', np.mean(arr, axis=1))

arr>>>
 [[1 2 3]
 [4 5 6]]
----------
전체 평균 : 3.5
열별 평균(axis=0) : [2.5 3.5 4.5]
행별 평균(axis=1) : [2. 5.]


In [19]:
# --------------------
# 누적합계(cumsum)
# --------------------

arr = np.arange(1, 7)
print('arr>>>\n', arr)
print('----------')
print('누적합계>>> \n', np.cumsum(arr))

arr>>>
 [1 2 3 4 5 6]
----------
누적합계>>> 
 [ 1  3  6 10 15 21]


In [20]:
# --------------------
# 최소값의 인덱스(argmix)
# 최대값의 인덱스(argmax)
# --------------------

np.random.seed(0)
arr = np.random.randint(1, 100, 10)
print(arr)
print('----------')
print('최소값의 인덱스:', np.argmin(arr))
print('최소값:', np.min(arr))
print('----------')
print('최대값의 인덱스:', np.argmax(arr))
print('최대값:', np.max(arr))

[45 48 65 68 68 10 84 22 37 88]
----------
최소값의 인덱스: 5
최소값: 10
----------
최대값의 인덱스: 9
최대값: 88
