In [1]:
import numpy as np

## 배열의 shape 제어

#### `배열객체.reshape()`
* `배열객체.reshape(shape)`
* size의 갯수만 맞다면 자유롭게 shape를 변경할 수 있다.
* -1을 적으면 배열의 size에 맞게 자동으로 갯수가 지정된다.

In [2]:
arr = np.arange(1, 7)
print('arr>>>', arr, '\n')

print('--- 3행 2열로 reshape ---')
print(arr.reshape(3, 2))

print('--- 2행 3열로 reshape ---')
print(arr.reshape(2, 3))

print('--- 6행 1열로 reshape ---')
print(arr.reshape(6, 1))

arr>>> [1 2 3 4 5 6] 

--- 3행 2열로 reshape ---
[[1 2]
 [3 4]
 [5 6]]
--- 2행 3열로 reshape ---
[[1 2 3]
 [4 5 6]]
--- 6행 1열로 reshape ---
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


#### `배열객체.flatten()`
* `배열객체.flatten()`
  * 다차원의 배열을 1차원으로 변경

In [3]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr)

print('----- flatten -----')
print(arr.flatten())

[[1 2]
 [3 4]
 [5 6]]
----- flatten -----
[1 2 3 4 5 6]


#### `배열객체.transpose()`

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

print('----- 배열 전치 -----')
print(arr.transpose())

[[1 2 3]
 [4 5 6]]
----- 배열 전치 -----
[[1 4]
 [2 5]
 [3 6]]


## 배열 연결
#### `np.concatenate()`
* `np.concatenate(연결할 배열 리스트, axis=축)`

In [5]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
arr3 = np.arange(9,13).reshape(2,2)

print('-- arr1 --\n', arr1, '\n')
print('-- arr2 --\n', arr2, '\n')
print('-- arr3 --\n', arr3, '\n')


print('----- 행 방향으로 concatenate -----')
print(np.concatenate([arr1, arr2, arr3], axis=0))


print('----- 열 방향으로 concatenate -----')
print(np.concatenate([arr1, arr2, arr3], axis=1))

-- arr1 --
 [[1 2]
 [3 4]] 

-- arr2 --
 [[5 6]
 [7 8]] 

-- arr3 --
 [[ 9 10]
 [11 12]] 

----- 행 방향으로 concatenate -----
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
----- 열 방향으로 concatenate -----
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


#### `np.vstack()`
* `np.vstack(연결할 배열리스트)` 
    * 수직방향(vertical) 연결
    * concatenate, axis=0과 동일


In [6]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
arr3 = np.arange(9,13).reshape(2,2)
print('-- arr1 --\n', arr1, '\n')
print('-- arr2 --\n', arr2, '\n')
print('-- arr3 --\n', arr3, '\n')

print('----- 수직방향 연결 -----')
print(np.vstack([arr1, arr2, arr3]))

-- arr1 --
 [[1 2]
 [3 4]] 

-- arr2 --
 [[5 6]
 [7 8]] 

-- arr3 --
 [[ 9 10]
 [11 12]] 

----- 수직방향 연결 -----
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


#### `np.hstack()` 
* `np.hstack(연결할 배열리스트)`
    * 수평방향(horizontal) 연결 
    * concatenate, axis=1과 동일

In [7]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
arr3 = np.arange(9,13).reshape(2,2)

print('-- arr1 --\n', arr1, '\n')
print('-- arr2 --\n', arr2, '\n')
print('-- arr3 --\n', arr3, '\n')

print('----- 수평방향 연결 -----')
print(np.hstack([arr1, arr2, arr3]))

-- arr1 --
 [[1 2]
 [3 4]] 

-- arr2 --
 [[5 6]
 [7 8]] 

-- arr3 --
 [[ 9 10]
 [11 12]] 

----- 수평방향 연결 -----
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]
